apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
    color: blue   # initially point to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
