name: K8s Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Determine active deployment
        id: color
        run: |
          ACTIVE_COLOR=$(kubectl get deployment ${{ secrets.DEPLOYMENT_NAME }} -n ${{ secrets.NAMESPACE }} -o jsonpath='{.metadata.labels.color}' || echo "blue")
          if [ "$ACTIVE_COLOR" == "blue" ]; then
            echo "INACTIVE_COLOR=green" >> $GITHUB_ENV
          else
            echo "INACTIVE_COLOR=blue" >> $GITHUB_ENV
          fi

      - name: Deploy new version
        run: |
          envsubst < k8s/deployment-template.yaml | kubectl apply -n ${{ secrets.NAMESPACE }} -f -

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/${{ secrets.DEPLOYMENT_NAME }}-${{ env.INACTIVE_COLOR }} -n ${{ secrets.NAMESPACE }} --timeout=120s

      - name: Switch Service to new deployment
        run: |
          kubectl patch service my-app -n ${{ secrets.NAMESPACE }} -p '{"spec":{"selector":{"app":"my-app","color":"'"${{ env.INACTIVE_COLOR }}"'"}}}'

      - name: Cleanup old deployment
        run: |
          OLD_COLOR=$( [ "${{ env.INACTIVE_COLOR }}" == "blue" ] && echo "green" || echo "blue" )
          kubectl delete deployment ${{ secrets.DEPLOYMENT_NAME }}-$OLD_COLOR -n ${{ secrets.NAMESPACE }} || true








